# Generated by Django 3.2.25 on 2025-04-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=255, verbose_name='معرف جدول البيانات')),
                ('credentials_file', models.FileField(upload_to='google_credentials/', verbose_name='ملف بيانات الاعتماد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='تفعيل المزامنة التلقائية')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='فترة المزامنة (بالدقائق)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('sync_customers', models.BooleanField(default=True, verbose_name='مزامنة العملاء')),
                ('sync_orders', models.BooleanField(default=True, verbose_name='مزامنة الطلبات')),
                ('sync_products', models.BooleanField(default=True, verbose_name='مزامنة المنتجات')),
                ('sync_inspections', models.BooleanField(default=True, verbose_name='مزامنة المعاينات')),
                ('sync_installations', models.BooleanField(default=True, verbose_name='مزامنة التركيبات')),
            ],
            options={
                'verbose_name': 'إعدادات مزامنة جوجل',
                'verbose_name_plural': 'إعدادات مزامنة جوجل',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('status', models.CharField(choices=[('success', 'ناجحة'), ('partial', 'نجاح جزئي'), ('failed', 'فاشلة')], max_length=20, verbose_name='الحالة')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='عدد السجلات المزامنة')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت بواسطة')),
            ],
            options={
                'verbose_name': 'سجل المزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
