# Generated by Django 3.2.25 on 2025-05-04 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=255, verbose_name='معرف جدول البيانات')),
                ('credentials_file', models.FileField(upload_to='google_credentials/', verbose_name='ملف بيانات الاعتماد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='تفعيل المزامنة التلقائية')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='فترة المزامنة (بالدقائق)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('sync_customers', models.BooleanField(default=True, verbose_name='مزامنة العملاء')),
                ('sync_orders', models.BooleanField(default=True, verbose_name='مزامنة الطلبات')),
                ('sync_products', models.BooleanField(default=True, verbose_name='مزامنة المنتجات')),
                ('sync_inspections', models.BooleanField(default=True, verbose_name='مزامنة المعاينات')),
                ('sync_installations', models.BooleanField(default=True, verbose_name='مزامنة التركيبات')),
                ('sync_company_info', models.BooleanField(default=True, verbose_name='مزامنة معلومات الشركة')),
                ('sync_contact_details', models.BooleanField(default=True, verbose_name='مزامنة بيانات التواصل')),
                ('sync_system_settings', models.BooleanField(default=True, verbose_name='مزامنة إعدادات النظام')),
            ],
            options={
                'verbose_name': 'إعدادات مزامنة جوجل',
                'verbose_name_plural': 'إعدادات مزامنة جوجل',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('company_info', 'معلومات الشركة'), ('contact_details', 'بيانات التواصل'), ('system_settings', 'إعدادات النظام')], max_length=50, verbose_name='القسم')),
                ('key', models.CharField(max_length=100, verbose_name='المفتاح')),
                ('value', models.TextField(blank=True, null=True, verbose_name='القيمة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['category', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('status', models.CharField(choices=[('success', 'ناجحة'), ('partial', 'نجاح جزئي'), ('failed', 'فاشلة')], max_length=20, verbose_name='الحالة')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='عدد السجلات المزامنة')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت بواسطة')),
            ],
            options={
                'verbose_name': 'سجل المزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت النسخ')),
                ('backup_type', models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي'), ('pre_import', 'قبل الاستيراد')], max_length=20, verbose_name='نوع النسخ')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.IntegerField(verbose_name='حجم الملف')),
                ('status', models.CharField(choices=[('success', 'نجاح'), ('failed', 'فشل'), ('restored', 'تمت الاستعادة')], max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('metadata', models.JSONField(default=dict, verbose_name='البيانات الوصفية')),
                ('file_checksum', models.CharField(max_length=64, verbose_name='التحقق من سلامة الملف')),
                ('backup_location', models.CharField(max_length=255, verbose_name='موقع النسخة الاحتياطية')),
                ('is_compressed', models.BooleanField(default=True, verbose_name='مضغوط')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='مشفر')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'سجل النسخ الاحتياطي',
                'verbose_name_plural': 'سجلات النسخ الاحتياطي',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='backuphistory',
            index=models.Index(fields=['-timestamp'], name='data_backup_timesta_8a34b0_idx'),
        ),
        migrations.AddIndex(
            model_name='backuphistory',
            index=models.Index(fields=['backup_type', 'status'], name='data_backup_backup__47e9c9_idx'),
        ),
    ]
