# Generated by Django 5.2 on 2025-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetsconfig',
            name='sync_company_info',
            field=models.BooleanField(default=True, verbose_name='مزامنة معلومات الشركة'),
        ),
        migrations.AddField(
            model_name='googlesheetsconfig',
            name='sync_contact_details',
            field=models.BooleanField(default=True, verbose_name='مزامنة بيانات التواصل'),
        ),
        migrations.AddField(
            model_name='googlesheetsconfig',
            name='sync_system_settings',
            field=models.BooleanField(default=True, verbose_name='مزامنة إعدادات النظام'),
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('company_info', 'معلومات الشركة'), ('contact_details', 'بيانات التواصل'), ('system_settings', 'إعدادات النظام')], max_length=50, verbose_name='القسم')),
                ('key', models.CharField(max_length=100, verbose_name='المفتاح')),
                ('value', models.TextField(blank=True, null=True, verbose_name='القيمة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['category', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
