# Generated by Django 3.2.25 on 2025-05-04 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='تفعيل النسخ الاحتياطي التلقائي')),
                ('interval', models.CharField(choices=[('daily', 'يومياً'), ('weekly', 'أسبوعياً'), ('monthly', 'شهرياً')], default='daily', max_length=20, verbose_name='الفترة')),
                ('time', models.TimeField(help_text='وقت تنفيذ النسخ الاحتياطي (بالتوقيت المحلي)', verbose_name='وقت التنفيذ')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='عدد الأيام التي سيتم الاحتفاظ بالنسخ الاحتياطية خلالها', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة الاحتفاظ (بالأيام)')),
                ('compression_enabled', models.BooleanField(default=True, verbose_name='تفعيل الضغط')),
                ('encryption_enabled', models.BooleanField(default=False, verbose_name='تفعيل التشفير')),
                ('encryption_key', models.CharField(blank=True, help_text='مفتاح التشفير للنسخ الاحتياطية (اتركه فارغاً إذا لم يكن التشفير مفعلاً)', max_length=255, null=True, verbose_name='مفتاح التشفير')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='آخر نسخ احتياطي')),
                ('next_backup', models.DateTimeField(blank=True, null=True, verbose_name='النسخ الاحتياطي التالي')),
            ],
            options={
                'verbose_name': 'إعدادات النسخ الاحتياطي التلقائي',
                'verbose_name_plural': 'إعدادات النسخ الاحتياطي التلقائي',
            },
        ),
        migrations.CreateModel(
            name='BackupNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_success', models.BooleanField(default=True, verbose_name='إشعار عند نجاح النسخ')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='إشعار عند فشل النسخ')),
                ('notify_on_restore', models.BooleanField(default=True, verbose_name='إشعار عند الاستعادة')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
    ]
