# Generated by Django 3.2.25 on 2025-05-04 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_backup', '0002_autobackupconfig_backupnotificationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('backup_size', models.BigIntegerField()),
                ('successful', models.BooleanField(default=True)),
                ('duration', models.FloatField()),
                ('storage_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('s3', 'Amazon S3')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'إحصائيات النسخ الاحتياطي',
                'verbose_name_plural': 'إحصائيات النسخ الاحتياطي',
                'ordering': ['-backup_date'],
            },
        ),
        migrations.CreateModel(
            name='CloudStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('s3', 'Amazon S3')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('auto_upload', models.BooleanField(default=False)),
                ('retention_period', models.IntegerField(default=30)),
                ('google_credentials', models.FileField(blank=True, null=True, upload_to='google_credentials/')),
                ('google_folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('aws_access_key', models.CharField(blank=True, max_length=100, null=True)),
                ('aws_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('aws_bucket_name', models.CharField(blank=True, max_length=100, null=True)),
                ('aws_region', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات التخزين السحابي',
                'verbose_name_plural': 'إعدادات التخزين السحابي',
            },
        ),
    ]
