# Generated by Django 5.2 on 2025-05-13 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم قاعدة البيانات')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite')], max_length=20, verbose_name='نوع قاعدة البيانات')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='المضيف')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='المنفذ')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='كلمة المرور')),
                ('database_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم قاعدة البيانات')),
                ('connection_string', models.TextField(blank=True, null=True, verbose_name='سلسلة الاتصال')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد قاعدة البيانات',
                'verbose_name_plural': 'إعدادات قواعد البيانات',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز الإعداد')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم استخدامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ انتهاء الصلاحية')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
            ],
            options={
                'verbose_name': 'رمز إعداد',
                'verbose_name_plural': 'رموز الإعداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم النسخة الاحتياطية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('file', models.FileField(upload_to='db_backups/', verbose_name='ملف النسخة الاحتياطية')),
                ('backup_type', models.CharField(choices=[('full', 'نسخة كاملة'), ('partial', 'نسخة جزئية')], default='full', max_length=20, verbose_name='نوع النسخة الاحتياطية')),
                ('size', models.BigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('database_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='db_manager.databaseconfig', verbose_name='إعداد قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية لقاعدة البيانات',
                'verbose_name_plural': 'النسخ الاحتياطية لقواعد البيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='db_imports/', verbose_name='ملف الاستيراد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('log', models.TextField(blank=True, null=True, verbose_name='سجل العملية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_imports', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('database_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='db_manager.databaseconfig', verbose_name='إعداد قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'استيراد قاعدة بيانات',
                'verbose_name_plural': 'عمليات استيراد قواعد البيانات',
                'ordering': ['-created_at'],
            },
        ),
    ]
