# Generated by Django 4.2.9 on 2025-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseimport',
            name='clear_data',
            field=models.BooleanField(default=False, verbose_name='حذف البيانات القديمة'),
        ),
    ]
