# Generated by Django 4.2.9 on 2025-05-14 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم قاعدة البيانات')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite')], max_length=20, verbose_name='نوع قاعدة البيانات')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='المضيف')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='المنفذ')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='كلمة المرور')),
                ('database_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم قاعدة البيانات')),
                ('connection_string', models.TextField(blank=True, null=True, verbose_name='سلسلة الاتصال')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد قاعدة البيانات',
                'verbose_name_plural': 'إعدادات قواعد البيانات',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(max_length=100, verbose_name='معرف جدول البيانات')),
                ('credentials_file', models.FileField(upload_to='google_credentials/', verbose_name='ملف بيانات الاعتماد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sync_customers', models.BooleanField(default=True, verbose_name='مزامنة العملاء')),
                ('sync_products', models.BooleanField(default=True, verbose_name='مزامنة المنتجات')),
                ('sync_orders', models.BooleanField(default=True, verbose_name='مزامنة الطلبات')),
                ('sync_inventory', models.BooleanField(default=True, verbose_name='مزامنة المخزون')),
                ('sync_inspections', models.BooleanField(default=False, verbose_name='مزامنة المعاينات')),
                ('sync_installations', models.BooleanField(default=False, verbose_name='مزامنة التركيبات')),
                ('sync_company_info', models.BooleanField(default=False, verbose_name='مزامنة معلومات الشركة')),
                ('auto_sync', models.BooleanField(default=False, verbose_name='مزامنة تلقائية')),
                ('sync_interval', models.IntegerField(default=60, verbose_name='فترة المزامنة (بالدقائق)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات Google Sheets',
                'verbose_name_plural': 'إعدادات Google Sheets',
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('file', models.FileField(upload_to='import_templates/', verbose_name='ملف القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب استيراد',
                'verbose_name_plural': 'قوالب الاستيراد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرمز')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ انتهاء الصلاحية')),
            ],
            options={
                'verbose_name': 'رمز الإعداد',
                'verbose_name_plural': 'رموز الإعداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت المزامنة')),
                ('status', models.CharField(choices=[('success', 'نجاح'), ('partial', 'نجاح جزئي'), ('failed', 'فشل')], max_length=20, verbose_name='الحالة')),
                ('records_synced', models.IntegerField(default=0, verbose_name='عدد السجلات المزامنة')),
                ('errors', models.TextField(blank=True, verbose_name='الأخطاء')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_management.googlesheetsconfig')),
            ],
            options={
                'verbose_name': 'سجل المزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='db_imports/', verbose_name='ملف الاستيراد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('log', models.TextField(blank=True, null=True, verbose_name='سجل العملية')),
                ('clear_data', models.BooleanField(default=False, verbose_name='حذف البيانات القديمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_imports', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('database_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='data_management.databaseconfig', verbose_name='إعداد قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'استيراد قاعدة البيانات',
                'verbose_name_plural': 'عمليات استيراد قواعد البيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم النسخة الاحتياطية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('file', models.FileField(upload_to='db_backups/', verbose_name='ملف النسخة الاحتياطية')),
                ('backup_type', models.CharField(choices=[('full', 'كامل'), ('schema', 'هيكل فقط'), ('data', 'بيانات فقط')], default='full', max_length=20, verbose_name='نوع النسخة الاحتياطية')),
                ('size', models.BigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('database_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='data_management.databaseconfig', verbose_name='إعداد قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية لقاعدة البيانات',
                'verbose_name_plural': 'النسخ الاحتياطية لقواعد البيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('import', 'استيراد'), ('export', 'تصدير')], max_length=10, verbose_name='نوع العملية')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file', models.FileField(upload_to='imports_exports/', verbose_name='الملف')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('is_multi_sheet', models.BooleanField(default=False, verbose_name='ملف متعدد الصفحات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('records_count', models.IntegerField(default=0, verbose_name='عدد السجلات')),
                ('success_count', models.IntegerField(default=0, verbose_name='عدد السجلات الناجحة')),
                ('error_count', models.IntegerField(default=0, verbose_name='عدد السجلات الفاشلة')),
                ('error_details', models.TextField(blank=True, verbose_name='تفاصيل الأخطاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_export_logs', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'سجل استيراد/تصدير',
                'verbose_name_plural': 'سجلات الاستيراد/التصدير',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_type', 'status'], name='data_manage_operati_bb5079_idx'), models.Index(fields=['model_name'], name='data_manage_model_n_9995b6_idx'), models.Index(fields=['created_at'], name='data_manage_created_e2940b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت النسخ')),
                ('backup_type', models.CharField(choices=[('full', 'كامل'), ('partial', 'جزئي'), ('data_only', 'بيانات فقط'), ('schema_only', 'هيكل فقط')], max_length=20, verbose_name='نوع النسخ')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.IntegerField(verbose_name='حجم الملف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('restored', 'تمت الاستعادة')], max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('metadata', models.JSONField(default=dict, verbose_name='البيانات الوصفية')),
                ('file_checksum', models.CharField(max_length=64, verbose_name='التحقق من سلامة الملف')),
                ('backup_location', models.CharField(max_length=255, verbose_name='موقع النسخة الاحتياطية')),
                ('is_compressed', models.BooleanField(default=True, verbose_name='مضغوط')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='مشفر')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'سجل النسخ الاحتياطي',
                'verbose_name_plural': 'سجلات النسخ الاحتياطي',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='data_manage_timesta_58caf5_idx'), models.Index(fields=['backup_type', 'status'], name='data_manage_backup__c12763_idx')],
            },
        ),
    ]
