# Generated by Django 5.2 on 2025-05-18 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseimport',
            name='conflict_resolution',
            field=models.CharField(choices=[('skip', 'تخطي السجلات المتكررة'), ('overwrite', 'استبدال السجلات المتكررة'), ('keep_both', 'الاحتفاظ بالسجلات المتكررة')], default='skip', max_length=20, verbose_name='معالجة التضارب'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='failed_records',
            field=models.IntegerField(default=0, verbose_name='السجلات الفاشلة'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='import_customers',
            field=models.BooleanField(default=True, verbose_name='استيراد العملاء'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='import_inspections',
            field=models.BooleanField(default=True, verbose_name='استيراد الفحوصات'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='import_mode',
            field=models.CharField(choices=[('full', 'استيراد كامل'), ('merge', 'دمج البيانات'), ('update', 'تحديث البيانات'), ('selective', 'استيراد انتقائي')], default='merge', max_length=20, verbose_name='وضع الاستيراد'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='import_orders',
            field=models.BooleanField(default=True, verbose_name='استيراد الطلبات'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='import_products',
            field=models.BooleanField(default=True, verbose_name='استيراد المنتجات'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='import_settings',
            field=models.BooleanField(default=True, verbose_name='استيراد الإعدادات'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='import_users',
            field=models.BooleanField(default=False, verbose_name='استيراد المستخدمين'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='imported_records',
            field=models.IntegerField(default=0, verbose_name='السجلات المستوردة'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='skipped_records',
            field=models.IntegerField(default=0, verbose_name='السجلات المتخطاة'),
        ),
        migrations.AddField(
            model_name='databaseimport',
            name='total_records',
            field=models.IntegerField(default=0, verbose_name='إجمالي السجلات'),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_management_created_backups', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='databaseimport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_management_created_imports', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
    ]
