# Generated by Django 5.2 on 2025-05-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_databaseimport_conflict_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseimport',
            name='conflict_resolution',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='failed_records',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='import_customers',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='import_inspections',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='import_mode',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='import_orders',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='import_products',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='import_settings',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='import_users',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='imported_records',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='skipped_records',
        ),
        migrations.RemoveField(
            model_name='databaseimport',
            name='total_records',
        ),
    ]
