# Generated by Django 4.2.9 on 2025-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_remove_databaseimport_conflict_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseimport',
            name='ignore_source_db_info',
            field=models.BooleanField(default=True, verbose_name='تجاهل معلومات قاعدة البيانات المصدر'),
        ),
    ]
