# Generated by Django 5.2.1 on 2025-05-20 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم قاعدة البيانات"),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[("postgresql", "PostgreSQL")],
                        max_length=20,
                        verbose_name="نوع قاعدة البيانات",
                    ),
                ),
                (
                    "connection_info",
                    models.JSONField(default=dict, verbose_name="معلومات الاتصال"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قاعدة بيانات",
                "verbose_name_plural": "قواعد البيانات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="اسم النسخة الاحتياطية"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=255, verbose_name="مسار الملف"),
                ),
                (
                    "size",
                    models.BigIntegerField(default=0, verbose_name="الحجم (بايت)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="odoo_db_manager.database",
                        verbose_name="قاعدة البيانات",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخة احتياطية",
                "verbose_name_plural": "النسخ الاحتياطية",
                "ordering": ["-created_at"],
            },
        ),
    ]
