# Generated by Django 4.2.21 on 2025-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odoo_db_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="backup_type",
            field=models.CharField(
                choices=[
                    ("customers", "بيانات العملاء"),
                    ("users", "بيانات المستخدمين"),
                    ("settings", "إعدادات النظام"),
                    ("full", "كل البيانات"),
                ],
                default="full",
                max_length=20,
                verbose_name="نوع النسخة الاحتياطية",
            ),
        ),
        migrations.AlterField(
            model_name="database",
            name="db_type",
            field=models.CharField(
                choices=[("postgresql", "PostgreSQL"), ("sqlite3", "SQLite")],
                max_length=20,
                verbose_name="نوع قاعدة البيانات",
            ),
        ),
    ]
