# Generated by Django 4.2.21 on 2025-05-22 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odoo_db_manager', '0002_backup_backup_type_alter_database_db_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجدولة')),
                ('backup_type', models.CharField(choices=[('customers', 'بيانات العملاء'), ('users', 'بيانات المستخدمين'), ('settings', 'إعدادات النظام'), ('full', 'كل البيانات')], default='full', max_length=20, verbose_name='نوع النسخة الاحتياطية')),
                ('frequency', models.CharField(choices=[('hourly', 'كل ساعة'), ('daily', 'يومياً'), ('weekly', 'أسبوعياً'), ('monthly', 'شهرياً')], default='daily', max_length=20, verbose_name='التكرار')),
                ('hour', models.IntegerField(default=0, help_text='0-23', verbose_name='الساعة')),
                ('minute', models.IntegerField(default=0, help_text='0-59', verbose_name='الدقيقة')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], default=0, null=True, verbose_name='يوم الأسبوع')),
                ('day_of_month', models.IntegerField(blank=True, default=1, help_text='1-31', null=True, verbose_name='يوم الشهر')),
                ('max_backups', models.IntegerField(default=24, help_text='الحد الأقصى هو 24 نسخة', verbose_name='الحد الأقصى لعدد النسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل القادم')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_schedules', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='odoo_db_manager.database', verbose_name='قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'جدولة النسخ الاحتياطية',
                'verbose_name_plural': 'جدولة النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
    ]
