# Generated by Django 4.2.21 on 2025-05-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_db_manager', '0003_backupschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='مجدولة'),
        ),
    ]
