# Generated by Django 3.2.25 on 2025-04-23 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDBImportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='وصف')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='مستخدمين استيراد قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'صلاحية استيراد قاعدة البيانات',
                'verbose_name_plural': 'صلاحيات استيراد قاعدة البيانات',
            },
        ),
    ]
