# Generated by Django 3.2.25 on 2025-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemdbimportpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_inspection_technician',
            field=models.BooleanField(default=False, verbose_name='فني معاينة'),
        ),
    ]
