# Generated by Django 4.2.9 on 2025-05-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='نظام الخواجه', max_length=100, verbose_name='اسم النظام')),
                ('currency', models.CharField(choices=[('SAR', 'ريال سعودي'), ('EGP', 'جنيه مصري'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو'), ('AED', 'درهم إماراتي'), ('KWD', 'دينار كويتي'), ('QAR', 'ريال قطري'), ('BHD', 'دينار بحريني'), ('OMR', 'ريال عماني')], default='SAR', max_length=3, verbose_name='العملة')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='إصدار النظام')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('enable_email_notifications', models.BooleanField(default=False, verbose_name='تفعيل إشعارات البريد الإلكتروني')),
                ('items_per_page', models.PositiveIntegerField(default=20, verbose_name='عدد العناصر في الصفحة')),
                ('low_stock_threshold', models.PositiveIntegerField(default=20, verbose_name='حد المخزون المنخفض (%)')),
                ('enable_analytics', models.BooleanField(default=True, verbose_name='تفعيل التحليلات')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='رسالة الصيانة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
