# Generated by Django 4.2.9 on 2025-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_core',
            field=models.BooleanField(default=False, help_text='حدد هذا الخيار إذا كان هذا القسم من أقسام النظام الأساسية التي لا يمكن حذفها أو تعديلها', verbose_name='قسم أساسي'),
        ),
    ]
