# Generated by Django 3.2.25 on 2025-04-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='has_pages',
            field=models.BooleanField(default=False, help_text='حدد هذا الخيار إذا كان هذا القسم يحتوي على صفحات متعددة', verbose_name='يحتوي على صفحات'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.department', verbose_name='القسم الرئيسي'),
        ),
    ]
