# Generated by Django 4.2.9 on 2025-05-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_indexes'),
        ('accounts', '0005_department_is_core'),
    ]

    operations = [
    ]
