# Generated by Django 5.2 on 2025-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0002_add_indexes_0005_department_is_core'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='branch',
            name='branch_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='branch',
            name='branch_is_main_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='department_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='department_is_core_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='department_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='is_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='username_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='is_active_idx',
        ),
    ]
