# Generated by Django 5.2 on 2025-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20250429_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='copyright_text',
            field=models.CharField(blank=True, default='جميع الحقوق محفوظة لشركة الخواجة للستائر والمفروشات تطوير zakee tahawi', max_length=255, verbose_name='نص حقوق النشر'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='developer',
            field=models.CharField(blank=True, default='zakee tahawi', editable=False, max_length=100, verbose_name='المطور'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='شركة الخواجة للستائر والمفروشات', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='release_date',
            field=models.CharField(blank=True, default='2025-04-30', editable=False, max_length=50, verbose_name='تاريخ الإطلاق'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='version',
            field=models.CharField(blank=True, default='1.0.0', editable=False, max_length=50, verbose_name='إصدار النظام'),
        ),
    ]
