# Generated by Django 5.2 on 2025-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_companyinfo_copyright_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='Elkhawaga', editable=False, max_length=200),
        ),
    ]
