# Generated by Django 5.2 on 2025-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_companyinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عن النظام', max_length=100, verbose_name='عنوان الصفحة')),
                ('subtitle', models.CharField(default='نظام إدارة المصنع والعملاء', max_length=200, verbose_name='العنوان الفرعي')),
                ('system_version', models.CharField(default='1.0.0', editable=False, max_length=50, verbose_name='إصدار النظام')),
                ('system_release_date', models.CharField(default='2025-04-30', editable=False, max_length=50, verbose_name='تاريخ الإطلاق')),
                ('system_developer', models.CharField(default='zakee tahawi', editable=False, max_length=100, verbose_name='المطور')),
                ('system_description', models.TextField(default='نظام متكامل لإدارة العملاء والمبيعات والإنتاج والمخزون', verbose_name='وصف النظام')),
            ],
            options={
                'verbose_name': 'إعدادات صفحة عن النظام',
                'verbose_name_plural': 'إعدادات صفحة عن النظام',
            },
        ),
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='اتصل بنا', max_length=100, verbose_name='عنوان الصفحة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصفحة')),
                ('contact_email', models.EmailField(default='info@elkhawaga.com', max_length=254, verbose_name='البريد الإلكتروني للاتصال')),
                ('contact_phone', models.CharField(default='+20 123 456 7890', max_length=20, verbose_name='رقم الهاتف للاتصال')),
                ('contact_address', models.TextField(blank=True, null=True, verbose_name='عنوان المكتب')),
                ('contact_hours', models.CharField(default='9 صباحاً - 5 مساءً', max_length=100, verbose_name='ساعات العمل')),
                ('form_title', models.CharField(default='نموذج الاتصال', max_length=100, verbose_name='عنوان النموذج')),
                ('form_success_message', models.CharField(default='تم إرسال رسالتك بنجاح. سنتواصل معك قريباً.', max_length=200, verbose_name='رسالة النجاح')),
                ('form_error_message', models.CharField(default='يرجى ملء جميع الحقول المطلوبة.', max_length=200, verbose_name='رسالة الخطأ')),
            ],
            options={
                'verbose_name': 'إعدادات نموذج الاتصال',
                'verbose_name_plural': 'إعدادات نموذج الاتصال',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_column_title', models.CharField(default='عن الشركة', max_length=100, verbose_name='عنوان العمود الأيسر')),
                ('left_column_text', models.TextField(default='نظام متكامل لإدارة العملاء والمبيعات والإنتاج والمخزون', verbose_name='نص العمود الأيسر')),
                ('middle_column_title', models.CharField(default='روابط سريعة', max_length=100, verbose_name='عنوان العمود الأوسط')),
                ('right_column_title', models.CharField(default='تواصل معنا', max_length=100, verbose_name='عنوان العمود الأيمن')),
            ],
            options={
                'verbose_name': 'إعدادات تذييل الصفحة',
                'verbose_name_plural': 'إعدادات تذييل الصفحة',
            },
        ),
    ]
