# Generated by Django 5.2 on 2025-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_aboutpagesettings_contactformsettings_footersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='company_name',
            field=models.CharField(default='Elkhawaga', max_length=200, verbose_name='اسم الشركة'),
        ),
    ]
