# Generated by Django 5.2 on 2025-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contactformsettings_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='Elkhawaga', max_length=200, verbose_name='اسم الشركة'),
        ),
    ]
