# Generated by Django 3.2.25 on 2025-04-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransactionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سبب حركة مخزون',
                'verbose_name_plural': 'أسباب حركة المخزون',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.stocktransactionreason', verbose_name='السبب'),
        ),
    ]
