# Generated by Django 3.2.25 on 2025-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransactionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='السبب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'سبب حركة المخزون',
                'verbose_name_plural': 'أسباب حركات المخزون',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'قطعة'), ('meter', 'متر'), ('sqm', 'متر مربع'), ('kg', 'كيلوجرام')], max_length=20, verbose_name='الوحدة'),
        ),
    ]
