# Generated by Django 3.2.25 on 2025-04-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20250426_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocktransactionreason', verbose_name='السبب'),
        ),
    ]
