# Generated by Django 3.2.25 on 2025-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20250426_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'قطعة'), ('meter', 'متر'), ('sqm', 'متر مربع'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('ton', 'طن'), ('liter', 'لتر'), ('ml', 'ملليلتر'), ('pack', 'علبة'), ('box', 'صندوق'), ('gallon', 'جالون'), ('dozen', 'دزينة'), ('ft', 'قدم'), ('yd', 'ياردة'), ('cm', 'سنتيمتر'), ('mm', 'ملليمتر'), ('bag', 'كيس'), ('carton', 'كرتون')], default='piece', max_length=10, verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'وارد'), ('out', 'صادر'), ('transfer', 'تحويل'), ('adjustment', 'تسوية'), ('return', 'إرجاع'), ('damage', 'تلف')], max_length=15, verbose_name='نوع الحركة'),
        ),
    ]
