# Generated by Django 3.2.25 on 2025-04-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktransaction_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.warehouse', verbose_name='المخزن'),
        ),
    ]
