# Generated by Django 3.2.25 on 2025-04-26 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_customer_branch_nullable'),
        ('inventory', '0006_alter_stocktransaction_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('purchase', 'توريد من مورد'), ('customer', 'توريد لعميل'), ('transfer', 'تحويل بين مخازن')], max_length=20, verbose_name='نوع الطلب')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب/الإذن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('actual_transfer_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل الفعلي')),
                ('customer_invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم فاتورة العميل')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='رقم العقد')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التنفيذ'), ('accepted', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='العميل')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_supply_orders', to='inventory.warehouse', verbose_name='المخزن المصدر')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='المورد')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_supply_orders', to='inventory.warehouse', verbose_name='المخزن المستلم')),
            ],
            options={
                'verbose_name': 'طلب توريد',
                'verbose_name_plural': 'طلبات التوريد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('delivered_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة/المسلمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='الصنف')),
                ('supply_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supplyorder', verbose_name='طلب التوريد')),
            ],
            options={
                'verbose_name': 'عنصر طلب توريد',
                'verbose_name_plural': 'عناصر طلبات التوريد',
            },
        ),
    ]
