# Generated by Django 3.2.25 on 2025-04-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplyorder_supplyorderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyorder',
            options={'ordering': ['-created_at'], 'permissions': [('can_execute_supplyorder', 'يمكنه تنفيذ طلبات التوريد')], 'verbose_name': 'طلب التوريد', 'verbose_name_plural': 'طلبات التوريد'},
        ),
    ]
