# Generated by Django 3.2.25 on 2025-04-26 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_branch_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_alter_supplyorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم طلب العميل')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='العميل')),
            ],
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='actual_transfer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل الفعلي'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='invoice_contract_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة/العقد'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار القبول'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=15, verbose_name='حالة الحركة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transfer_party',
            field=models.CharField(blank=True, max_length=100, verbose_name='جهة التحويل'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transfer_permission_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم إذن التحويل'),
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.customerorder', verbose_name='طلب العميل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='الصنف')),
            ],
        ),
    ]
