# Generated by Django 4.2.9 on 2025-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales', 'تقرير المبيعات'), ('production', 'تقرير الإنتاج'), ('inventory', 'تقرير المخزون'), ('financial', 'تقرير مالي'), ('analytics', 'تقرير تحليلي'), ('custom', 'تقرير مخصص')], max_length=20, verbose_name='نوع التقرير'),
        ),
    ]
