# Generated by Django 5.2 on 2025-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_merge_0002_add_indexes_0002_alter_report_report_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='report_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_creator_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='schedule_report_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='schedule_frequency_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='schedule_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='schedule_creator_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='schedule_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedreport',
            name='saved_report_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedreport',
            name='saved_report_creator_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedreport',
            name='saved_report_created_idx',
        ),
    ]
