# Generated by Django 3.2.25 on 2025-04-17 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('file', models.FileField(upload_to='import_templates/', verbose_name='ملف القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب استيراد',
                'verbose_name_plural': 'قوالب الاستيراد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('import', 'استيراد'), ('export', 'تصدير')], max_length=10, verbose_name='نوع العملية')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file', models.FileField(upload_to='imports_exports/', verbose_name='الملف')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('is_multi_sheet', models.BooleanField(default=False, verbose_name='ملف متعدد الصفحات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='عدد السجلات')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='عدد النجاحات')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('error_details', models.TextField(blank=True, verbose_name='تفاصيل الأخطاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_export_logs', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'سجل استيراد/تصدير',
                'verbose_name_plural': 'سجلات الاستيراد/التصدير',
                'ordering': ['-created_at'],
            },
        ),
    ]
