# Generated by Django 3.2.25 on 2025-04-17 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم العقد')),
                ('request_date', models.DateField(verbose_name='تاريخ طلب المعاينة')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ تنفيذ المعاينة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='pending', max_length=10, verbose_name='الحالة')),
                ('result', models.CharField(blank=True, choices=[('passed', 'ناجحة'), ('failed', 'غير مجدية')], max_length=10, null=True, verbose_name='النتيجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='accounts.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'معاينة',
                'verbose_name_plural': 'المعاينات',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('custom', 'مخصص')], max_length=10, verbose_name='نوع التقرير')),
                ('date_from', models.DateField(verbose_name='من تاريخ')),
                ('date_to', models.DateField(verbose_name='إلى تاريخ')),
                ('total_inspections', models.IntegerField(default=0, verbose_name='إجمالي المعاينات')),
                ('successful_inspections', models.IntegerField(default=0, verbose_name='المعاينات الناجحة')),
                ('pending_inspections', models.IntegerField(default=0, verbose_name='المعاينات المعلقة')),
                ('cancelled_inspections', models.IntegerField(default=0, verbose_name='المعاينات الملغاة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء التقرير')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='accounts.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير معاينات',
                'verbose_name_plural': 'تقارير المعاينات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scheduled', 'موعد معاينة'), ('reminder', 'تذكير'), ('status_change', 'تغيير الحالة'), ('evaluation', 'تقييم جديد')], max_length=20, verbose_name='نوع التنبيه')),
                ('message', models.TextField(verbose_name='نص التنبيه')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنبيه')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='موعد التنبيه')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inspections.inspection', verbose_name='المعاينة')),
            ],
            options={
                'verbose_name': 'تنبيه معاينة',
                'verbose_name_plural': 'تنبيهات المعاينات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('location', 'الموقع'), ('condition', 'الحالة'), ('suitability', 'الملاءمة'), ('safety', 'السلامة'), ('accessibility', 'سهولة الوصول')], max_length=20, verbose_name='معيار التقييم')),
                ('rating', models.IntegerField(choices=[(1, 'ضعيف'), (2, 'مقبول'), (3, 'جيد'), (4, 'جيد جداً'), (5, 'ممتاز')], verbose_name='التقييم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_created', to=settings.AUTH_USER_MODEL, verbose_name='تم التقييم بواسطة')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='inspections.inspection', verbose_name='المعاينة')),
            ],
            options={
                'verbose_name': 'تقييم المعاينة',
                'verbose_name_plural': 'تقييمات المعاينات',
            },
        ),
    ]
