# Generated by Django 3.2.25 on 2025-04-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكتمال'),
        ),
    ]
