# Generated by Django 3.2.25 on 2025-04-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspection_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionevaluation',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inspections.inspection', verbose_name='المعاينة'),
        ),
    ]
