# Generated by Django 3.2.25 on 2025-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_inspectionevaluation_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_file',
            field=models.FileField(blank=True, null=True, upload_to='inspections/files/', verbose_name='ملف المعاينة'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_from_orders',
            field=models.BooleanField(default=False, verbose_name='من قسم الطلبات'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='windows_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الشبابيك'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('scheduled', 'مجدول'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
    ]
