# Generated by Django 3.2.25 on 2025-04-27 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20250427_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0005_auto_20250427_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='orders.order', verbose_name='الطلب المرتبط'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
    ]
