# Generated by Django 3.2.25 on 2025-04-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee'),
        ('inspections', '0006_auto_20250427_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_inspections', to='accounts.employee', verbose_name='الموظف المسؤول'),
        ),
    ]
