# Generated by Django 3.2.25 on 2025-04-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_salesperson'),
        ('inspections', '0007_inspection_responsible_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='accounts.salesperson', verbose_name='البائع'),
        ),
    ]
