# Generated by Django 3.2.25 on 2025-04-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_alter_inspection_responsible_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='order_notes',
            field=models.TextField(blank=True, help_text='نسخة ثابتة من ملاحظات الطلب', verbose_name='ملاحظات الطلب'),
        ),
    ]
