# Generated by Django 4.2.9 on 2025-05-06 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20250505_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('warehouse', 'في المستودع'), ('factory', 'في المصنع'), ('cutting', 'قيد القص'), ('ready', 'جاهز للتسليم'), ('delivered', 'تم التسليم')], max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('warehouse', 'في المستودع'), ('factory', 'في المصنع'), ('cutting', 'قيد القص'), ('ready', 'جاهز للتسليم'), ('delivered', 'تم التسليم')], max_length=20, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سجل حالة الطلب',
                'verbose_name_plural': 'سجلات حالة الطلب',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='status_log_order_idx'), models.Index(fields=['created_at'], name='status_log_date_idx')],
            },
        ),
    ]
