# Generated by Django 3.2.25 on 2025-04-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
