# Generated by Django 4.2.9 on 2025-05-07 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('rule_type', models.CharField(choices=[('seasonal', 'موسمي'), ('quantity', 'كمية'), ('customer_type', 'نوع العميل'), ('special_offer', 'عرض خاص')], max_length=20, verbose_name='نوع القاعدة')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الخصم')),
                ('min_quantity', models.IntegerField(blank=True, null=True, verbose_name='الحد الأدنى للكمية')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للمبلغ')),
                ('customer_type', models.CharField(blank=True, choices=[('regular', 'عادي'), ('vip', 'VIP'), ('wholesale', 'جملة'), ('distributor', 'موزع')], max_length=20, null=True, verbose_name='نوع العميل')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'التسعير الديناميكي',
                'verbose_name_plural': 'قواعد التسعير الديناميكي',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر النهائي'),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='آخر تحديث للطلب'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_changed',
            field=models.BooleanField(default=False, help_text='يشير إلى ما إذا تم تغيير السعر مؤخراً'),
        ),
        migrations.AddField(
            model_name='order',
            name='dynamic_pricing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.dynamicpricing', verbose_name='قاعدة التسعير'),
        ),
    ]
