# Generated by Django 3.2.25 on 2025-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_salesperson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_types',
            field=models.JSONField(default=list, verbose_name='أنواع الطلب المختارة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('product', 'منتج'), ('service', 'خدمة')], max_length=10, null=True),
        ),
    ]
