# Generated by Django 3.2.25 on 2025-04-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee'),
        ('orders', '0004_auto_20250427_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='responsible_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee', verbose_name='الموظف المسؤول'),
        ),
    ]
