# Generated by Django 4.2.9 on 2025-05-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dynamicpricing_order_final_price_order_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_provider', models.CharField(choices=[('internal', 'خدمة التوصيل الداخلية'), ('aramex', 'أرامكس'), ('smsa', 'سمسا'), ('dhl', 'دي إتش إل')], default='internal', max_length=20, verbose_name='شركة الشحن')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التتبع')),
                ('shipping_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('scheduled', 'تم جدولة الشحن'), ('picked_up', 'تم استلام الشحنة'), ('in_transit', 'قيد النقل'), ('out_for_delivery', 'خارج للتوصيل'), ('delivered', 'تم التوصيل'), ('failed', 'فشل التوصيل')], default='pending', max_length=20, verbose_name='حالة الشحن')),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوصيل المتوقع')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوصيل الفعلي')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة الشحن')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='اسم المستلم')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='رقم هاتف المستلم')),
                ('shipping_notes', models.TextField(blank=True, verbose_name='ملاحظات الشحن')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تفاصيل الشحن',
                'verbose_name_plural': 'تفاصيل الشحن',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='shipping_order_idx'), models.Index(fields=['shipping_status'], name='shipping_status_idx'), models.Index(fields=['tracking_number'], name='shipping_tracking_idx')],
            },
        ),
    ]
