# Generated by Django 3.2.25 on 2025-04-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_responsible_employee'),
    ]

    operations = [
    ]
