# Generated by Django 4.2.9 on 2025-05-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_shippingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dynamic_pricing_rule',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_changed',
        ),
        migrations.DeleteModel(
            name='DynamicPricing',
        ),
    ]
