# Generated by Django 4.2.9 on 2025-05-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_dynamic_pricing_rule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
    ]
