# Generated by Django 3.2.25 on 2025-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20250428_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesperson',
            options={'ordering': ['name'], 'verbose_name': 'بائع', 'verbose_name_plural': 'البائعون'},
        ),
        migrations.AddField(
            model_name='salesperson',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterUniqueTogether(
            name='salesperson',
            unique_together=set(),
        ),
    ]
