# Generated by Django 3.2.25 on 2025-04-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_salesperson'),
        ('orders', '0007_auto_20250428_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='responsible_employee',
        ),
        migrations.AlterField(
            model_name='order',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.salesperson', verbose_name='البائع'),
        ),
        migrations.DeleteModel(
            name='Salesperson',
        ),
    ]
