# Generated by Django 4.2.9 on 2025-05-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_add_indexes'),
        ('installations', '0003_auto_20250507_0639'),
    ]

    operations = [
    ]
